#!/bin/bash

#Libraries need a ldconfig

ldconfig

useradd -m pi

gpasswd -a pi video

echo "allowed_users=anybody" > /etc/X11/Xwrapper.config

cp /app/xinitrc /home/pi/.xinitrc;
chown pi: /home/pi/.xinitrc

su - pi -c startx &
